name: Nice Shoes
favicon: null
layout_spectrum: 0.44347064499743283
typography_spectrum: 0.5091179036535323
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.0814916668459773
  lightness: 0.06132565322332084
  saturation: 0.6157919059041888
  rhythmicContrast: 0.23248459165915847
purpose: []
